name = "DiffusionFlux"
uuid = "0088ed5a-e206-4379-b0fa-25d85632c804"
authors = ["Vinod Janardhanan"]
version = "0.1.0"

[compat]
julia = "1.8.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
